Adding RoadRunner bridge
spiral/app pull request #48
Opened 2022-02-03 20:50 UTC by msmakouz

2022-02-07 08:08 UTC, butschster requested changes

2022-02-07 08:09 UTC, butschster commented on app/config/storage.php
> +    'servers' => [],
Like here https://github.com/laravel/laravel/blob/8.x/config/filesystems.php

2022-02-07 14:55 UTC, msmakouz commented on .env.sample
> +APP_ENV=local
https://github.com/spiral/app/pull/48/files#diff-e03916ee184162a7a5a895daa276c181668689505daaa0a72e500c24f9007c38R19

I followed the example here: 
https://github.com/spiral/cycle-bridge/blob/master/README.md?plain=1#L348 

I think we need to standardize the variable name and possible values.

2022-02-07 15:03 UTC, msmakouz commented on README.md
> +$ ./vendor/bin/rr get
Changed to get-binary

2022-02-08 11:24 UTC, msmakouz commented on app/config/cache.php
> +    'typeAliases' => [
Added RR cache config examples

2022-02-08 11:25 UTC, msmakouz commented on app/config/grpc.php
> +    'binaryPath' => null,
Added link

2022-02-09 12:06 UTC, butschster approved these changes

2022-02-09 12:07 UTC, merged